help: help_doxy help_sphinx

help_doxy:
	@echo "-------------------------------"
	@echo "doxygen sample commands"
	@echo "-------------------------------"
	@echo "doxygen && cd latex && make pdf"
	@echo ""


help_sphinx:
	@echo "-------------------------------"
	@echo "sphinx sample commands"
	@echo "-------------------------------"
	@echo "cd sphinx_doc && make latexpdf"

